name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bookshare
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      
      - name: Copy test env file
        run: cp .env.test .env

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
        env:
          DOTENV_CONFIG_PATH: .env

      - name: Run go vet
        run: go vet ./...
        env:
          DOTENV_CONFIG_PATH: .env

      - name: Check formatting
        run: test -z "$(gofmt -s -l .)"

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
